apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashraf-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashraf
  template:
    metadata:
      labels:
        app: ashraf
    spec:
      containers:
      - name: ashraf
        image: mohamedashraf3/mohamedashraf:test 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  type: NodePort
  selector:
    app: ashraf
  ports:
    - port: 6000
      targetPort: 8000
      nodePort: 32000